name: mosaic_for_mobile
description: "A mobile implementation of MOSAIC"
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - mosaic-logo.png

